// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/duchuanyou/Desktop/未命名文件夹 4/react-ui/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
