import type { GanttColumn, GanttRow } from './types'

export const column: GanttColumn[] = [
  {
    title: '类型',
    dataIndex: 'model',
    key: 'model',
    width: '300px',
  },
  {
    title: '设备',
    dataIndex: 'seat',
    key: 'seat',
  },
  {
    title: '机号',
    dataIndex: 'type',
    key: 'type',
  },
  {
    title: '布局',
    dataIndex: 'typeName',
    key: 'typeName',
  },
  //   {
  //     title: "备注",
  //     dataIndex: "remark",
  //   },
]

export const ganttData: GanttRow[] = [
  {
    id: 'r1',
    model: 1,
    seat: '1楼',
    type: '转台1',
    typeName: '转台',
    // remark: "备注 \nasdsa /n sadsad",
    blockList: [
      {
        id: 'r1-1',
        equipmentId: 'r1',
        projectName: '测试项目1',
        status: '1',
        startTime: '2025-04-01',
        endTime: '2025-04-5',
        isValidate: '1',
      },
    ],
  },
  {
    id: 'r2',
    model: 1,
    seat: '2楼',
    type: '转台2',
    typeName: '转台',
    // remark: "备注 \nasdsa /n sadsad",
    blockList: [
      {
        id: 'r2-1',
        equipmentId: 'r2',
        projectName: '测试项目2',
        status: '1',
        startTime: '2025-04-06',
        endTime: '2025-04-12',
        isValidate: '1',
      },
      {
        id: 'r2-2',
        equipmentId: 'r2',
        projectName: '测试项目3',
        status: '1',
        startTime: '2025-04-14',
        endTime: '2025-04-15',
        isValidate: '1',
      },
    ],
  },
  {
    id: 'r3',
    model: 1,
    seat: '2楼',
    type: '转台2',
    typeName: '转台',
    // remark: "备注 \nasdsa /n sadsad",
    blockList: [
      {
        id: 'r3-1',
        equipmentId: 'r2',
        projectName: '测试项目2',
        status: '1',
        startTime: '2025-04-05',
        endTime: '2025-04-08',
        isValidate: '1',
      },
      {
        id: 'r3-2',
        equipmentId: 'r2',
        projectName: '测试项目3',
        status: '1',
        startTime: '2025-04-09',
        endTime: '2025-04-15',
        isValidate: '1',
      },
    ],
  },
  {
    id: 'r4',
    model: 1,
    seat: '2楼',
    type: '转台2',
    typeName: '转台',
    // remark: "备注 \nasdsa /n sadsad",
    blockList: [
      {
        id: 'r4-1',
        equipmentId: 'r2',
        projectName: '测试项目2',
        status: '0',
        startTime: '2025-03-17',
        endTime: '2025-03-19',
        isValidate: '1',
      },
      {
        id: 'r4-2',
        equipmentId: 'r2',
        projectName: '测试项目3',
        status: '0',
        startTime: '2025-03-20',
        endTime: '2025-03-30',
        isValidate: '1',
      },
    ],
  },
  {
    id: 'r5',
    model: 1,
    seat: '2楼',
    type: '转台2',
    typeName: '转台',
    // remark: "备注 \nasdsa /n sadsad",
    blockList: [
      {
        id: 'r5-1',
        equipmentId: 'r2',
        projectName: '测试项目2',
        status: '2',
        startTime: '2025-03-17',
        endTime: '2025-03-19',
        isValidate: '1',
      },
      {
        id: 'r5-2',
        equipmentId: 'r2',
        projectName: '测试项目3',
        status: '2',
        startTime: '2025-03-20',
        endTime: '2025-03-30',
        isValidate: '1',
      },
    ],
  },
  {
    id: 'r6',
    model: 1,
    seat: '2楼',
    type: '转台2',
    typeName: '转台',
    // remark: "备注 \nasdsa /n sadsad",
    blockList: [
      {
        id: 'r6-1',
        equipmentId: 'r2',
        projectName: '测试项目2',
        status: '3',
        startTime: '2025-03-17',
        endTime: '2025-03-19',
        isValidate: '1',
      },
      {
        id: 'r6-2',
        equipmentId: 'r2',
        projectName: '测试项目3',
        status: '3',
        startTime: '2025-03-20',
        endTime: '2025-03-30',
        isValidate: '1',
      },
    ],
  },
]
