// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/gantt-chart":{"path":"components/gantt-chart","id":"docs/components/gantt-chart","parentId":"DocLayout"},"docs/components/checkbox":{"path":"components/checkbox","id":"docs/components/checkbox","parentId":"DocLayout"},"docs/components/teleport":{"path":"components/teleport","id":"docs/components/teleport","parentId":"DocLayout"},"docs/components/button":{"path":"components/button","id":"docs/components/button","parentId":"DocLayout"},"docs/components/charts":{"path":"components/charts","id":"docs/components/charts","parentId":"DocLayout"},"docs/components/dialog":{"path":"components/dialog","id":"docs/components/dialog","parentId":"DocLayout"},"docs/components/group":{"path":"components/group","id":"docs/components/group","parentId":"DocLayout"},"docs/components/input":{"path":"components/input","id":"docs/components/input","parentId":"DocLayout"},"docs/components/form":{"path":"components/form","id":"docs/components/form","parentId":"DocLayout"},"docs/components/icon":{"path":"components/icon","id":"docs/components/icon","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/duchuanyou/Desktop/cursor_ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/duchuanyou/Desktop/cursor_ui/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/duchuanyou/Desktop/cursor_ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/components/gantt-chart': React.lazy(() => import(/* webpackChunkName: "docs__components__gantt-chart.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/gantt-chart.md')),
'docs/components/checkbox': React.lazy(() => import(/* webpackChunkName: "docs__components__checkbox.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/checkbox.md')),
'docs/components/teleport': React.lazy(() => import(/* webpackChunkName: "docs__components__teleport.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/teleport.md')),
'docs/components/button': React.lazy(() => import(/* webpackChunkName: "docs__components__button.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/button.md')),
'docs/components/charts': React.lazy(() => import(/* webpackChunkName: "docs__components__charts.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/charts.md')),
'docs/components/dialog': React.lazy(() => import(/* webpackChunkName: "docs__components__dialog.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/dialog.md')),
'docs/components/group': React.lazy(() => import(/* webpackChunkName: "docs__components__group.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/group.md')),
'docs/components/input': React.lazy(() => import(/* webpackChunkName: "docs__components__input.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/input.md')),
'docs/components/form': React.lazy(() => import(/* webpackChunkName: "docs__components__form.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/form.md')),
'docs/components/icon': React.lazy(() => import(/* webpackChunkName: "docs__components__icon.md" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/icon.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/duchuanyou/Desktop/cursor_ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
