// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/gantt-chart.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/gantt-chart.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/checkbox.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/checkbox.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/teleport.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/teleport.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/button.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/button.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/charts.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/charts.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/dialog.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/dialog.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/group.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/group.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/input.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/input.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/table.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/table.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/form.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/form.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/icon.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/duchuanyou/Desktop/cursor_ui/docs/components/icon.md?type=demo-index';

export const filesMeta = {
  'docs/components/gantt-chart': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/gantt-chart.md?type=text'),
  },
  'docs/components/checkbox': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/checkbox.md?type=text'),
  },
  'docs/components/teleport': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/teleport.md?type=text'),
  },
  'docs/components/button': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/button.md?type=text'),
  },
  'docs/components/charts': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/charts.md?type=text'),
  },
  'docs/components/dialog': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/dialog.md?type=text'),
  },
  'docs/components/group': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/group.md?type=text'),
  },
  'docs/components/input': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/input.md?type=text'),
  },
  'docs/components/table': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/table.md?type=text'),
  },
  'docs/components/form': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/form.md?type=text'),
  },
  'docs/components/icon': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/duchuanyou/Desktop/cursor_ui/docs/components/icon.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
