// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/duchuanyou/Desktop/cursor_ui/node_modules/dumi/theme-default/slots/ContentTabs/index.js';
